services:
  # ----------------------------
  # Backend Service (Docker)
  # ----------------------------
  - type: web
    name: zx16-backend
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000

  # ----------------------------
  # Frontend Static Site
  # ----------------------------
  - type: static
    name: zx16-frontend
    buildCommand: ""
    staticPublishPath: app/Frontend
